services:
  php:
    build:
      context: .
    environment:
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"
    working_dir: /workspaces
    ports:
      - "127.0.0.1:8887:80"
    volumes:
      - ..:/workspaces
      - ../../doc-ja:/workspaces/ja
      - ../../doc-en:/workspaces/en
      - ./ini/php.ini:/usr/local/etc/php/conf.d/option.ini
  php84:
    build:
      context: .
      dockerfile: Dockerfile.php84
    environment:
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"
    working_dir: /sandbox
    volumes:
      - ../../sandbox:/sandbox
      - ./ini/php84.ini:/usr/local/etc/php/conf.d/php84.ini
    tty: true
